# Generated by Django 2.2.17 on 2021-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edescription', models.CharField(max_length=100)),
                ('ebaseunitofmeasure', models.CharField(max_length=100)),
                ('eprojectunitofmeasure', models.CharField(max_length=100)),
                ('econversionfactor', models.IntegerField()),
                ('econtractingentryref', models.IntegerField()),
                ('ematerialtype', models.CharField(max_length=100)),
                ('emasterformatcode', models.IntegerField()),
                ('euniformat', models.CharField(max_length=100)),
                ('eRBScode', models.IntegerField()),
                ('eWBSCODE', models.IntegerField()),
            ],
        ),
    ]
